import type {
  ActiveExpedition,
  AvatarConfig,
  Channel,
  ChatMessage,
  Contract,
  Expedition,
  FactionProject,
  Identity,
  InventoryItem,
  PartyMember,
  Profile,
  QuickAction,
  RecoveryResult,
  Skill,
  VanityItem,
} from "./types"

export const channels: Channel[] = [
  {
    id: "PUBLIC",
    label: "public",
    description: "General relay traffic.",
    unread: 0,
  },
  {
    id: "TRADE",
    label: "trade",
    description: "Item exchange, requests, social commerce.",
    unread: 2,
  },
  { id: "HELP", label: "help", description: "Questions and onboarding.", unread: 0 },
  { id: "LOG", label: "log", description: "Expedition activity and system events.", readOnly: true, unread: 0 },
  {
    id: "UNDERCHAT",
    label: "underchat",
    description: "Hidden relay traffic.",
    restricted: true,
    unread: 4,
  },
  {
    id: "GAME",
    label: "game",
    description: "System summaries and alerts.",
    readOnly: true,
    unread: 0,
  },
]

const now = 1_737_300_000_000

export const messages: ChatMessage[] = [
  // PUBLIC
  {
    id: "m1",
    channel: "PUBLIC",
    kind: "system",
    handle: "relay",
    body: "connecting to relay · 06 nodes reachable",
    at: now - 1000 * 60 * 42,
  },
  {
    id: "m2",
    channel: "PUBLIC",
    kind: "player",
    handle: "@veilrun",
    title: "Route Tender",
    titleRarity: "common",
    body: "anyone up for a courier run north? route is calm tonight",
    at: now - 1000 * 60 * 38,
  },
  {
    id: "m3",
    channel: "PUBLIC",
    kind: "player",
    handle: "@palesignal",
    title: "Signal Keeper",
    titleRarity: "uncommon",
    body: "relay 04 is drifting again, second time this week",
    at: now - 1000 * 60 * 31,
  },
  {
    id: "m4",
    channel: "PUBLIC",
    kind: "player",
    handle: "@nineofdust",
    body: "i have two salvage plates if anyone is building",
    at: now - 1000 * 60 * 22,
  },
  {
    id: "m5",
    channel: "PUBLIC",
    kind: "player",
    handle: "@veilrun",
    title: "Route Tender",
    titleRarity: "common",
    body: "@nineofdust — trade tab, sending",
    at: now - 1000 * 60 * 21,
  },
  {
    id: "m6",
    channel: "PUBLIC",
    kind: "player",
    handle: "@lantern.ix",
    body: "new handle here. do titles stack or are they one per identity",
    at: now - 1000 * 60 * 14,
  },
  {
    id: "m7",
    channel: "PUBLIC",
    kind: "player",
    handle: "@palesignal",
    title: "Signal Keeper",
    titleRarity: "uncommon",
    body: "one per identity, second slot is cosmetic only",
    at: now - 1000 * 60 * 13,
  },
  {
    id: "m8",
    channel: "PUBLIC",
    kind: "player",
    handle: "@echoform",
    body: "route west of the depot is still pressured, avoid for now",
    at: now - 1000 * 60 * 6,
  },
  {
    id: "m9",
    channel: "PUBLIC",
    kind: "player",
    handle: "@veilrun",
    title: "Route Tender",
    titleRarity: "common",
    body: "confirmed, took it an hour ago — convoy had to reroute",
    at: now - 1000 * 60 * 4,
  },

  // TRADE
  {
    id: "t1",
    channel: "TRADE",
    kind: "player",
    handle: "@nineofdust",
    body: "WTS salvage plate x2, 3 tokens each",
    at: now - 1000 * 60 * 28,
  },
  {
    id: "t2",
    channel: "TRADE",
    kind: "player",
    handle: "@smallhollow",
    body: "WTB archive fragments, paying above token rate",
    at: now - 1000 * 60 * 20,
  },
  {
    id: "t3",
    channel: "TRADE",
    kind: "player",
    handle: "@quietsparrow",
    body: "field kit schematic trade, looking for signal beacon plans",
    at: now - 1000 * 60 * 12,
  },
  {
    id: "t4",
    channel: "TRADE",
    kind: "player",
    handle: "@nineofdust",
    body: "plates sold, thanks",
    at: now - 1000 * 60 * 9,
  },

  // HELP
  {
    id: "h1",
    channel: "HELP",
    kind: "player",
    handle: "@lantern.ix",
    body: "how do i equip a variant skill, is it automatic",
    at: now - 1000 * 60 * 18,
  },
  {
    id: "h2",
    channel: "HELP",
    kind: "player",
    handle: "@smallhollow",
    body: "skills page, long press the skill card. variant shows a lilac dot",
    at: now - 1000 * 60 * 17,
  },
  {
    id: "h3",
    channel: "HELP",
    kind: "player",
    handle: "@lantern.ix",
    body: "got it, thanks",
    at: now - 1000 * 60 * 16,
  },

  // LOG — expedition activity feed
  {
    id: "l1",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] signal trace initiated · target: sector 7-alpha",
    at: now - 1000 * 60 * 120,
  },
  {
    id: "l2",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] signal trace complete · recovered: faded data packet x2",
    at: now - 1000 * 60 * 85,
  },
  {
    id: "l3",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[party] @palesignal joined your party",
    at: now - 1000 * 60 * 60,
  },
  {
    id: "l4",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] archive dive initiated · estimated duration: 45m",
    at: now - 1000 * 60 * 55,
  },
  {
    id: "l5",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[skill] scavenging advanced to level 3",
    at: now - 1000 * 60 * 40,
  },
  {
    id: "l6",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[recovery] reconstructed packet · result: refined schematic (rare)",
    at: now - 1000 * 60 * 25,
  },
  {
    id: "l7",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] archive dive progress: 67% · signal stable",
    at: now - 1000 * 60 * 12,
  },

  // UNDERCHAT — quieter, more careful tone
  {
    id: "u1",
    channel: "UNDERCHAT",
    kind: "system",
    handle: "relay",
    body: "underchat access granted · traffic not logged to registry",
    at: now - 1000 * 60 * 70,
  },
  {
    id: "u2",
    channel: "UNDERCHAT",
    kind: "player",
    handle: "@deepcall",
    title: "Relay Warden",
    titleRarity: "epic",
    body: "the singular packet is back in rotation. three listeners this cycle.",
    at: now - 1000 * 60 * 34,
  },
  {
    id: "u3",
    channel: "UNDERCHAT",
    kind: "player",
    handle: "@palesignal",
    title: "Signal Keeper",
    titleRarity: "uncommon",
    body: "route it through me next window. i can carry it without a trace.",
    at: now - 1000 * 60 * 33,
  },
  {
    id: "u4",
    channel: "UNDERCHAT",
    kind: "player",
    handle: "@deepcall",
    title: "Relay Warden",
    titleRarity: "epic",
    body: "understood. window opens at the next rest.",
    at: now - 1000 * 60 * 32,
  },
  {
    id: "u5",
    channel: "UNDERCHAT",
    kind: "whisper",
    handle: "@unknown",
    body: "you have been listening. keep it that way.",
    at: now - 1000 * 60 * 11,
  },

  // GAME — read only
  {
    id: "g1",
    channel: "GAME",
    kind: "system",
    handle: "relay",
    body: "expedition · archive_dive · completed · rewards staged",
    at: now - 1000 * 60 * 25,
  },
  {
    id: "g2",
    channel: "GAME",
    kind: "system",
    handle: "relay",
    body: "signal_pull · standard · 1 packet recovered",
    at: now - 1000 * 60 * 19,
  },
  {
    id: "g3",
    channel: "GAME",
    kind: "system",
    handle: "relay",
    body: "party · @veilrun accepted invite",
    at: now - 1000 * 60 * 7,
  },
  {
    id: "g4",
    channel: "GAME",
    kind: "system",
    handle: "relay",
    body: "daily relay reset in 04:12:06",
    at: now - 1000 * 60 * 1,
  },
]

export const expeditions: Expedition[] = [
  {
    id: "signal_trace",
    label: "Signal Trace",
    duration: 900,
    risk: "Low",
    tags: ["recon", "relay"],
    requiredSkill: "surveying",
    suggestedParty: 1,
    rewards: { xp: 35, tokens: 1, materials: ["scrap_wire x3", "relay_glass"] },
  },
  {
    id: "archive_dive",
    label: "Archive Dive",
    duration: 1200,
    risk: "Medium",
    tags: ["archive", "analysis"],
    requiredSkill: "analysis",
    suggestedParty: 2,
    rewards: {
      xp: 45,
      tokens: 2,
      materials: ["archive_fragments x2", "dusted_filament x2"],
    },
  },
  {
    id: "courier_run",
    label: "Courier Run",
    duration: 780,
    risk: "Low",
    tags: ["supply", "logistics"],
    requiredSkill: "logistics",
    suggestedParty: 1,
    rewards: {
      xp: 30,
      tokens: 1,
      materials: ["packed_rations x2", "route_stamps x2"],
    },
  },
  {
    id: "scavenger_sweep",
    label: "Scavenger Sweep",
    duration: 1020,
    risk: "Medium",
    tags: ["salvage", "materials"],
    requiredSkill: "scavenging",
    suggestedParty: 2,
    rewards: {
      xp: 40,
      tokens: 1,
      materials: ["relay_scrap x4", "salvage_plate x2"],
    },
  },
  {
    id: "faction_relay",
    label: "Faction Relay",
    duration: 1500,
    risk: "Medium",
    tags: ["faction", "support"],
    requiredSkill: "networking",
    suggestedParty: 3,
    rewards: {
      xp: 55,
      tokens: 2,
      materials: ["faction_seal", "route_stamps x3"],
    },
  },
]

export const activeExpedition: ActiveExpedition = {
  id: "archive_dive",
  label: "Archive Dive",
  progress: 0.62,
  etaSeconds: 420,
  log: [
    "archive fragment found",
    "pattern stabilized",
    "signal noise clearing...",
  ],
}

export const skills: Skill[] = [
  {
    id: "scavenging",
    label: "Scavenging",
    summary: "Improves material yield on recovery runs.",
    level: 6,
    maxLevel: 10,
    locked: false,
  },
  {
    id: "analysis",
    label: "Analysis",
    summary: "Improves archive quality and discovery rolls.",
    level: 8,
    maxLevel: 10,
    locked: false,
    variant: "Deep Read",
  },
  {
    id: "fabrication",
    label: "Fabrication",
    summary: "Improves crafting output and build efficiency.",
    level: 4,
    maxLevel: 10,
    locked: false,
  },
  {
    id: "logistics",
    label: "Logistics",
    summary: "Improves prep efficiency and supply throughput.",
    level: 5,
    maxLevel: 10,
    locked: false,
  },
  {
    id: "networking",
    label: "Networking",
    summary: "Supports contracts, invites, coordination.",
    level: 3,
    maxLevel: 10,
    locked: false,
  },
  {
    id: "surveying",
    label: "Surveying",
    summary: "Improves recon and zone-pressure reads.",
    level: 7,
    maxLevel: 10,
    locked: false,
    variant: "Long Sight",
  },
  {
    id: "recovery",
    label: "Recovery",
    summary: "Improves repair actions and safe returns.",
    level: 2,
    maxLevel: 10,
    locked: false,
  },
  {
    id: "security",
    label: "Security",
    summary: "Improves hostile-event mitigation.",
    level: 0,
    maxLevel: 10,
    locked: true,
  },
  {
    id: "cartography",
    label: "Cartography",
    summary: "Unstable. Requires an archive key to open.",
    level: 0,
    maxLevel: 10,
    locked: true,
  },
]

export const inventory: InventoryItem[] = [
  {
    id: "relay_glass",
    label: "Relay Glass",
    aspect: "relay",
    rarity: "uncommon",
    qty: 4,
    identified: true,
    description: "A polished shard that holds a channel tone. Warm to the touch.",
  },
  {
    id: "archive_fragments",
    label: "Archive Fragments",
    aspect: "archive",
    rarity: "uncommon",
    qty: 6,
    identified: true,
    description: "Broken index packets. Reconstruct at the Archive station.",
  },
  {
    id: "salvage_plate",
    label: "Salvage Plate",
    aspect: "salvage",
    rarity: "common",
    qty: 2,
    identified: true,
    description: "Plated scrap, safe to handle. Good for trade.",
  },
  {
    id: "packed_rations",
    label: "Packed Rations",
    aspect: "supply",
    rarity: "common",
    qty: 8,
    identified: true,
    description: "Quiet calories. Suitable for longer routes.",
  },
  {
    id: "faction_seal",
    label: "Faction Seal",
    aspect: "relay",
    rarity: "rare",
    qty: 1,
    identified: true,
    description: "Authorizes one handoff inside a faction relay.",
  },
  {
    id: "unstable_imprint",
    label: "Unstable Imprint",
    aspect: "unknown",
    rarity: "epic",
    qty: 1,
    identified: false,
    description:
      "Signal irregular. Aspect not yet resolved. Run through the Archive to stabilize.",
  },
  {
    id: "glass_signal",
    label: "Glass Signal",
    aspect: "cosmetic",
    rarity: "epic",
    qty: 1,
    identified: true,
    description: "A chat flair. Your handle rings softly when you speak.",
  },
]

// Pre-defined static avatar configs to avoid hydration issues
// These are deterministic results from generateAvatarFromSeed
const playerAvatar: AvatarConfig = {
  seed: "@routetender.07",
  layers: [
    { type: "base", variant: 0, color: 2 },
    { type: "eyes", variant: 1, color: 1 },
    { type: "mouth", variant: 0 },
    { type: "hair", variant: 2, color: 3 },
    { type: "accessory", variant: 1 }, // glasses
    { type: "hat", variant: 0 },
    { type: "flair", variant: 0 },
  ],
}

const palesignalAvatar: AvatarConfig = {
  seed: "@palesignal",
  layers: [
    { type: "base", variant: 1, color: 1 },
    { type: "eyes", variant: 0, color: 2 },
    { type: "mouth", variant: 1 },
    { type: "hair", variant: 1, color: 1 },
    { type: "accessory", variant: 0 },
    { type: "hat", variant: 0 },
    { type: "flair", variant: 0 },
  ],
}

const archivistAvatar: AvatarConfig = {
  seed: "@archivist.mm",
  layers: [
    { type: "base", variant: 0, color: 3 },
    { type: "eyes", variant: 2, color: 0 },
    { type: "mouth", variant: 2 },
    { type: "hair", variant: 3, color: 2 },
    { type: "accessory", variant: 0 },
    { type: "hat", variant: 1 },
    { type: "flair", variant: 0 },
  ],
}

export const party: PartyMember[] = [
  {
    slot: 1,
    handle: "@you",
    title: "Route Tender",
    titleRarity: "common",
    role: "Logistics",
    status: "ready",
    leader: true,
    avatar: playerAvatar,
  },
  {
    slot: 2,
    handle: "@palesignal",
    title: "Signal Keeper",
    titleRarity: "uncommon",
    role: "Surveying",
    status: "ready",
    avatar: palesignalAvatar,
  },
  {
    slot: 3,
    handle: "@archivist.mm",
    title: "Archive Listener",
    titleRarity: "rare",
    role: "Analysis",
    status: "idle",
    avatar: archivistAvatar,
  },
  // slot 4 is empty (invite slot)
]

export const recoveryResults: RecoveryResult[] = [
  {
    id: "r1",
    label: "Relay Flair",
    type: "chat_flair",
    rarity: "common",
    recoveredAt: now - 1000 * 60 * 60 * 4,
  },
  {
    id: "r2",
    label: "Signal Keeper",
    type: "title",
    rarity: "uncommon",
    recoveredAt: now - 1000 * 60 * 60 * 9,
  },
  {
    id: "r3",
    label: "Field Kit Schematic",
    type: "schematic",
    rarity: "common",
    recoveredAt: now - 1000 * 60 * 60 * 18,
  },
  {
    id: "r4",
    label: "Archive Listener",
    type: "title",
    rarity: "rare",
    recoveredAt: now - 1000 * 60 * 60 * 26,
  },
  {
    id: "r5",
    label: "Glass Signal",
    type: "cosmetic",
    rarity: "epic",
    recoveredAt: now - 1000 * 60 * 60 * 40,
  },
]

export const identity: Identity = {
  handle: "@routetender.07",
  title: "Route Tender",
  titleRarity: "common",
  established: true,
  avatar: playerAvatar,
}

/** Shard currencies surfaced on the Archive page. */
export const shards = {
  relay_tokens: 14,
  deep_signals: 2,
  signal_salvage: 6,
}

export const quickActions: QuickAction[] = [
  {
    id: "qa1",
    label: "Claim Rewards",
    description: "Archive Dive complete",
    priority: "urgent",
    deeplink: { screen: "ops", tab: "expeditions" },
  },
  {
    id: "qa2",
    label: "Contract Deadline",
    description: "Salvage Run expires in 2h",
    priority: "urgent",
    deeplink: { screen: "contracts" },
  },
  {
    id: "qa3",
    label: "Faction Event",
    description: "Supply Drive active",
    priority: "normal",
    deeplink: { screen: "faction" },
  },
]

export const contracts: Contract[] = [
  {
    id: "c1",
    label: "Salvage Run",
    issuer: "Waykeepers",
    description: "Recover 3 salvage plates from the western depot.",
    reward: "45 XP, 2 Relay Tokens",
    deadline: "2h",
    status: "active",
  },
  {
    id: "c2",
    label: "Signal Survey",
    issuer: "Archive Collective",
    description: "Map signal nodes in sector 7-alpha.",
    reward: "60 XP, Archive Fragment",
    deadline: "8h",
    status: "available",
  },
  {
    id: "c3",
    label: "Courier Escort",
    issuer: "Route Guild",
    description: "Accompany a courier on the northern route.",
    reward: "35 XP, 1 Relay Token",
    status: "available",
  },
  {
    id: "c4",
    label: "Archive Recovery",
    issuer: "Archive Collective",
    description: "Retrieve unstable data packets from a corrupted node.",
    reward: "80 XP, Deep Signal",
    deadline: "12h",
    status: "available",
  },
]

export const factionProjects: FactionProject[] = [
  {
    id: "fp1",
    label: "Supply Drive",
    description: "Collect supplies for the western outpost reconstruction.",
    progress: 847,
    goal: 1000,
    contributors: 23,
  },
  {
    id: "fp2",
    label: "Signal Network",
    description: "Extend relay coverage to sector 9.",
    progress: 312,
    goal: 500,
    contributors: 15,
  },
  {
    id: "fp3",
    label: "Archive Index",
    description: "Catalog recovered fragments from the deep archive.",
    progress: 156,
    goal: 400,
    contributors: 8,
  },
]

// Unlocked vanity items
export const vanityItems: VanityItem[] = [
  { id: "v1", label: "Signal Glasses", layerType: "accessory", variant: 1, rarity: "common", unlocked: true, equipped: true },
  { id: "v2", label: "Route Cap", layerType: "hat", variant: 1, rarity: "common", unlocked: true, equipped: false },
  { id: "v3", label: "Eyepatch", layerType: "accessory", variant: 2, rarity: "uncommon", unlocked: true, equipped: false },
  { id: "v4", label: "Archive Visor", layerType: "accessory", variant: 4, rarity: "rare", unlocked: true, equipped: false },
  { id: "v5", label: "Signal Antenna", layerType: "hat", variant: 3, rarity: "uncommon", unlocked: true, equipped: false },
  { id: "v6", label: "Relay Horns", layerType: "hat", variant: 4, rarity: "rare", unlocked: false, equipped: false },
  { id: "v7", label: "Archive Halo", layerType: "hat", variant: 5, rarity: "epic", unlocked: false, equipped: false },
  { id: "v8", label: "Crown of Routes", layerType: "hat", variant: 6, rarity: "legendary", unlocked: false, equipped: false },
  { id: "v9", label: "Static Aura", layerType: "flair", variant: 2, rarity: "epic", unlocked: false, equipped: false },
  { id: "v10", label: "Sparkle Effect", layerType: "flair", variant: 3, rarity: "rare", unlocked: false, equipped: false },
]

export const profile: Profile = {
  handle: "@routetender.07",
  title: {
    id: "route_tender",
    label: "Route Tender",
    rarity: "common",
    equipped: true,
  },
  faction: {
    id: "waykeepers",
    label: "Waykeepers",
    rank: 2,
    standing: 340,
    maxStanding: 500,
  },
  level: 14,
  xp: 2840,
  xpToNext: 3200,
  vanityItems: vanityItems,
  ownedTitles: [
    {
      id: "route_tender",
      label: "Route Tender",
      rarity: "common",
      equipped: true,
    },
    {
      id: "signal_keeper",
      label: "Signal Keeper",
      rarity: "uncommon",
      equipped: false,
    },
    {
      id: "archive_listener",
      label: "Archive Listener",
      rarity: "rare",
      equipped: false,
    },
    {
      id: "relay_initiate",
      label: "Relay Initiate",
      rarity: "common",
      equipped: false,
    },
  ],
  badges: [
    {
      id: "first_expedition",
      label: "First Steps",
      description: "Completed your first expedition.",
      earnedAt: now - 1000 * 60 * 60 * 24 * 14,
    },
    {
      id: "archive_recovered",
      label: "Archive Touched",
      description: "Recovered your first archive fragment.",
      earnedAt: now - 1000 * 60 * 60 * 24 * 10,
    },
    {
      id: "faction_joined",
      label: "Aligned",
      description: "Joined a faction.",
      earnedAt: now - 1000 * 60 * 60 * 24 * 7,
    },
  ],
  notifications: [
    {
      id: 1,
      title: "Expedition Complete",
      body: "Your Archive Dive has finished. Rewards are ready to claim.",
      priority: "high",
      state: "unread",
      deeplink: { screen: "expedition" },
      createdAt: now - 1000 * 60 * 12,
    },
    {
      id: 2,
      title: "Faction Standing",
      body: "Your standing with the Waykeepers increased by 45.",
      priority: "normal",
      state: "unread",
      createdAt: now - 1000 * 60 * 38,
    },
    {
      id: 3,
      title: "New Title Unlocked",
      body: "You earned the Signal Keeper title from signal recovery.",
      priority: "normal",
      state: "read",
      deeplink: { screen: "profile" },
      createdAt: now - 1000 * 60 * 60 * 2,
    },
    {
      id: 4,
      title: "Party Invite",
      body: "@palesignal invited you to join their party.",
      priority: "high",
      state: "read",
      deeplink: { screen: "party" },
      createdAt: now - 1000 * 60 * 60 * 4,
    },
  ],
}
