import type {
  ActiveExpedition,
  AvatarConfig,
  Channel,
  ChatMessage,
  Contract,
  Expedition,
  FactionProject,
  Identity,
  InventoryItem,
  PartyMember,
  Profile,
  QuickAction,
  RecoveryResult,
  Skill,
  VanityItem,
} from "./types"

export const channels: Channel[] = [
  {
    id: "PUBLIC",
    label: "public",
    description: "General relay traffic.",
    unread: 0,
    pinnedCount: 1,
    memberCount: 47,
  },
  {
    id: "TRADE",
    label: "trade",
    description: "Item exchange, requests, social commerce.",
    unread: 2,
  },
  {
    id: "PARTY",
    label: "party",
    description: "Your party's private channel.",
    unread: 0,
    memberCount: 3,
  },
  {
    id: "FACTION",
    label: "faction",
    description: "Waykeepers internal communications.",
    restricted: true,
    unread: 1,
    memberCount: 23,
  },
{
  id: "GAME",
  label: "game",
  description: "Server announcements, events, and system alerts.",
  readOnly: true,
  unread: 0,
  },
  { id: "HELP", label: "help", description: "Questions and onboarding.", unread: 0 },
  { id: "LOG", label: "log", description: "Your expedition logs, faction activity, and contract progress.", readOnly: true, unread: 0 },
  {
    id: "UNDERCHAT",
    label: "underchat",
    description: "Hidden relay traffic.",
    restricted: true,
    unread: 4,
  },
]

const now = 1_737_300_000_000

export const messages: ChatMessage[] = [
  // PUBLIC
  {
    id: "m1",
    channel: "PUBLIC",
    kind: "system",
    handle: "relay",
    body: "connecting to relay · 06 nodes reachable",
    at: now - 1000 * 60 * 42,
  },
  {
    id: "m-pinned",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay4f8c1",
    title: "Relay Warden",
    titleRarity: "epic",
    body: "Maintenance window tonight 02:00-04:00 UTC. Relays 03-05 will be offline for signal calibration.",
    at: now - 1000 * 60 * 60 * 2,
    pinned: true,
  },
  {
    id: "m-legendary",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay9d2e7",
    title: "Stormway Hierophant",
    titleRarity: "legendary",
    body: "The old routes remember. Walk them with respect.",
    at: now - 1000 * 60 * 45,
  },
  {
    id: "m-mythic",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay1b5a9",
    title: "Shardheart Ascendant",
    titleRarity: "mythic",
    body: "New relay coordinates logged for the deep archives. Safe travels, couriers.",
    at: now - 1000 * 60 * 40,
  },
  {
    id: "m2",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay6c4d3",
    title: "Route Tender",
    titleRarity: "common",
    body: "anyone up for a courier run north? route is calm tonight",
    at: now - 1000 * 60 * 38,
  },
  {
    id: "m3",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay3e8f2",
    title: "Signal Keeper",
    titleRarity: "uncommon",
    body: "relay 04 is drifting again, second time this week",
    at: now - 1000 * 60 * 31,
  },
  {
    id: "m4",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay8b1c5",
    body: "i have two salvage plates if anyone is building",
    at: now - 1000 * 60 * 22,
  },
  {
    id: "m5",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay6c4d3",
    title: "Route Tender",
    titleRarity: "common",
    body: "@nineofdust — trade tab, sending",
    at: now - 1000 * 60 * 21,
  },
  {
    id: "m6",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay2d9a4",
    body: "new handle here. do titles stack or are they one per identity",
    at: now - 1000 * 60 * 14,
  },
  {
    id: "m7",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay3e8f2",
    title: "Signal Keeper",
    titleRarity: "uncommon",
    body: "one per identity, second slot is cosmetic only",
    at: now - 1000 * 60 * 13,
  },
  {
    id: "m8",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay5f7b8",
    body: "route west of the depot is still pressured, avoid for now",
    at: now - 1000 * 60 * 6,
  },
  {
    id: "m9",
    channel: "PUBLIC",
    kind: "player",
    handle: "@Relay6c4d3",
    title: "Route Tender",
    titleRarity: "common",
    body: "confirmed, took it an hour ago — convoy had to reroute",
    at: now - 1000 * 60 * 4,
  },

  // TRADE
  {
    id: "t1",
    channel: "TRADE",
    kind: "player",
    handle: "@Relay8b1c5",
    body: "WTS salvage plate x2, 3 tokens each",
    at: now - 1000 * 60 * 28,
  },
  {
    id: "t2",
    channel: "TRADE",
    kind: "player",
    handle: "@Relay0e3c6",
    body: "WTB archive fragments, paying above token rate",
    at: now - 1000 * 60 * 20,
  },
  {
    id: "t3",
    channel: "TRADE",
    kind: "player",
    handle: "@Relay4a2d1",
    body: "field kit schematic trade, looking for signal beacon plans",
    at: now - 1000 * 60 * 12,
  },
  {
    id: "t4",
    channel: "TRADE",
    kind: "player",
    handle: "@Relay8b1c5",
    body: "plates sold, thanks",
    at: now - 1000 * 60 * 9,
  },

  // HELP
  {
    id: "h1",
    channel: "HELP",
    kind: "player",
    handle: "@Relay2d9a4",
    body: "how do i equip a variant skill, is it automatic",
    at: now - 1000 * 60 * 18,
  },
  {
    id: "h2",
    channel: "HELP",
    kind: "player",
    handle: "@Relay0e3c6",
    body: "skills page, long press the skill card. variant shows a lilac dot",
    at: now - 1000 * 60 * 17,
  },
  {
    id: "h3",
    channel: "HELP",
    kind: "player",
    handle: "@Relay2d9a4",
    body: "got it, thanks",
    at: now - 1000 * 60 * 16,
  },

  // LOG — personal expedition and faction activity logs
  {
    id: "l1",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] Signal Trace started · sector 7-alpha · party: solo",
    at: now - 1000 * 60 * 180,
  },
  {
    id: "l2",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] Signal Trace complete · materials: scrap wire x4, relay glass x2 · +35 XP",
    at: now - 1000 * 60 * 150,
  },
  {
    id: "l3",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[faction] Hearth Wardens standing increased · +15 · current: 1,247",
    at: now - 1000 * 60 * 120,
  },
  {
    id: "l4",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] Scavenger Sweep started · western depot · party: @Relay3e8f2, @Relay6c4d3",
    at: now - 1000 * 60 * 90,
  },
  {
    id: "l5",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[contract] 'Scavenger Sweep: Western Depot' progress · 2/3 salvage plates recovered",
    at: now - 1000 * 60 * 75,
  },
  {
    id: "l6",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] Scavenger Sweep complete · materials: salvage plate x3, iron scrap x5 · +40 XP",
    at: now - 1000 * 60 * 60,
  },
  {
    id: "l7",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[contract] 'Scavenger Sweep: Western Depot' complete · rewards: 40 XP, 2 Relay Tokens",
    at: now - 1000 * 60 * 59,
  },
  {
    id: "l8",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[skill] Scavenging advanced · level 5 → 6 · +5% material yield",
    at: now - 1000 * 60 * 58,
  },
  {
    id: "l9",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] Archive Dive started · deep sector · party: solo",
    at: now - 1000 * 60 * 45,
  },
  {
    id: "l10",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[expedition] Archive Dive in progress · 67% complete · signal stable",
    at: now - 1000 * 60 * 20,
  },
  {
    id: "l11",
    channel: "LOG",
    kind: "system",
    handle: "relay",
    body: "[faction] Project contribution recorded · 'Outpost Reconstruction' · +12 progress",
    at: now - 1000 * 60 * 15,
  },

  // UNDERCHAT — quieter, more careful tone
  {
    id: "u1",
    channel: "UNDERCHAT",
    kind: "system",
    handle: "relay",
    body: "underchat access granted · traffic not logged to registry",
    at: now - 1000 * 60 * 70,
  },
  {
    id: "u2",
    channel: "UNDERCHAT",
    kind: "player",
    handle: "@Relay7c5e9",
    title: "Relay Warden",
    titleRarity: "epic",
    body: "the singular packet is back in rotation. three listeners this cycle.",
    at: now - 1000 * 60 * 34,
  },
  {
    id: "u3",
    channel: "UNDERCHAT",
    kind: "player",
    handle: "@Relay3e8f2",
    title: "Signal Keeper",
    titleRarity: "uncommon",
    body: "route it through me next window. i can carry it without a trace.",
    at: now - 1000 * 60 * 33,
  },
  {
    id: "u4",
    channel: "UNDERCHAT",
    kind: "player",
    handle: "@Relay7c5e9",
    title: "Relay Warden",
    titleRarity: "epic",
    body: "understood. window opens at the next rest.",
    at: now - 1000 * 60 * 32,
  },
  {
    id: "u5",
    channel: "UNDERCHAT",
    kind: "whisper",
    handle: "@Relay?????",
    body: "you have been listening. keep it that way.",
    at: now - 1000 * 60 * 11,
  },

  // GAME — system announcements and server-wide events only
  {
    id: "g1",
    channel: "GAME",
    kind: "system",
    handle: "system",
    body: "[announcement] Relay maintenance complete · all systems operational",
    at: now - 1000 * 60 * 240,
  },
  {
    id: "g2",
    channel: "GAME",
    kind: "system",
    handle: "system",
    body: "[event] Double XP weekend active · ends in 47:23:15",
    at: now - 1000 * 60 * 180,
  },
  {
    id: "g3",
    channel: "GAME",
    kind: "system",
    handle: "system",
    body: "[alert] Deep Archive sector 9 experiencing signal instability · expedition success rates reduced",
    at: now - 1000 * 60 * 120,
  },
  {
    id: "g4",
    channel: "GAME",
    kind: "system",
    handle: "system",
    body: "[event] Faction Rally: Hearth Wardens · contribute to 'Outpost Reconstruction' for bonus rewards",
    at: now - 1000 * 60 * 90,
  },
  {
    id: "g5",
    channel: "GAME",
    kind: "system",
    handle: "system",
    body: "[milestone] Server-wide: 10,000 Archive Dives completed this cycle · community reward unlocked",
    at: now - 1000 * 60 * 60,
  },
  {
    id: "g6",
    channel: "GAME",
    kind: "system",
    handle: "system",
    body: "[notice] New expedition available: 'Deep Pull' · requires Security skill level 3+",
    at: now - 1000 * 60 * 30,
  },
  {
    id: "g7",
    channel: "GAME",
    kind: "system",
    handle: "system",
    body: "[timer] Daily relay reset in 04:12:06 · contracts and bonuses will refresh",
    at: now - 1000 * 60 * 5,
  },
  {
    id: "g8",
    channel: "GAME",
    kind: "system",
    handle: "system",
    body: "[alert] Sector 7-alpha signal anomaly detected · rare materials spawning for next 2 hours",
    at: now - 1000 * 60 * 2,
  },
]

export const expeditions: Expedition[] = [
  {
    id: "signal_trace",
    label: "Signal Trace",
    duration: 900,
    risk: "Low",
    tags: ["recon", "relay"],
    requiredSkill: "surveying",
    suggestedParty: 1,
    rewards: { xp: 35, tokens: 1, materials: ["scrap_wire x3", "relay_glass"] },
  },
  {
    id: "archive_dive",
    label: "Archive Dive",
    duration: 1200,
    risk: "Medium",
    tags: ["archive", "analysis"],
    requiredSkill: "analysis",
    suggestedParty: 2,
    rewards: {
      xp: 45,
      tokens: 2,
      materials: ["archive_fragments x2", "dusted_filament x2"],
    },
  },
  {
    id: "courier_run",
    label: "Courier Run",
    duration: 780,
    risk: "Low",
    tags: ["supply", "logistics"],
    requiredSkill: "logistics",
    suggestedParty: 1,
    rewards: {
      xp: 30,
      tokens: 1,
      materials: ["packed_rations x2", "route_stamps x2"],
    },
  },
  {
    id: "scavenger_sweep",
    label: "Scavenger Sweep",
    description: "Search abandoned sectors for salvage materials.",
    duration: 1020,
    risk: "Medium",
    tags: ["salvage", "materials"],
    requiredSkill: "scavenging",
    suggestedParty: 2,
    minLevel: 5,
    rewards: {
      xp: 40,
      tokens: 1,
      materials: ["relay_scrap x4", "salvage_plate x2"],
      skillXp: [{ skill: "Scavenging", amount: 15 }],
      possibleDrops: [
        { label: "Salvage Plate", rarity: "common", chance: 0.5 },
        { label: "Archive Fragment", rarity: "uncommon", chance: 0.2 },
      ],
    },
  },
  {
    id: "relay_maintenance",
    label: "Relay Maintenance",
    description: "Repair and maintain signal relays across the network. Rewards standing with your current faction.",
    duration: 1500,
    risk: "Medium",
    tags: ["support", "networking"],
    requiredSkill: "networking",
    suggestedParty: 3,
    minLevel: 8,
    rewards: {
      xp: 55,
      tokens: 2,
      materials: ["relay_components x2", "route_stamps x3"],
      factionStanding: 25,
      skillXp: [{ skill: "Networking", amount: 20 }, { skill: "Logistics", amount: 10 }],
    },
  },
  {
    id: "supply_cache",
    label: "Supply Cache Recovery",
    description: "Locate and recover hidden supply caches from pre-collapse storage sites.",
    duration: 1080,
    risk: "Low",
    tags: ["supply", "recovery"],
    requiredSkill: "logistics",
    suggestedParty: 2,
    minLevel: 3,
    rewards: {
      xp: 35,
      tokens: 1,
      materials: ["packed_rations x4", "clean_water x3", "salvage_plate"],
      skillXp: [{ skill: "Logistics", amount: 15 }],
      possibleDrops: [
        { label: "Emergency Kit", rarity: "uncommon", chance: 0.25 },
      ],
    },
  },
  {
    id: "perimeter_sweep",
    label: "Perimeter Sweep",
    description: "Patrol and secure the outer boundaries. Good for leveling Security skill.",
    duration: 720,
    risk: "Medium",
    tags: ["security", "patrol"],
    requiredSkill: "security",
    suggestedParty: 2,
    minLevel: 1,
    rewards: {
      xp: 30,
      tokens: 1,
      materials: ["salvage_scrap x3"],
      skillXp: [{ skill: "Security", amount: 20 }],
    },
  },
  {
    id: "route_mapping",
    label: "Route Mapping",
    description: "Chart new paths through uncharted sectors. Unlocks shortcuts for future expeditions.",
    duration: 1800,
    risk: "Medium",
    tags: ["cartography", "exploration"],
    requiredSkill: "cartography",
    suggestedParty: 2,
    minLevel: 6,
    rewards: {
      xp: 50,
      tokens: 2,
      materials: ["map_fragment x2", "route_data"],
      skillXp: [{ skill: "Cartography", amount: 25 }, { skill: "Surveying", amount: 15 }],
      possibleDrops: [
        { label: "Hidden Route", rarity: "rare", chance: 0.1 },
      ],
    },
  },
  {
    id: "deep_archive",
    label: "Deep Archive Dive",
    description: "Venture into the unstable deep archives. High reward, high risk.",
    duration: 2400,
    risk: "High",
    tags: ["archive", "rare"],
    requiredSkill: "analysis",
    suggestedParty: 4,
    minLevel: 12,
    stages: [
      { id: "s1", label: "Descent", description: "Navigate the outer layers", duration: 600, risk: "Low" },
      { id: "s2", label: "Search", description: "Locate archive signatures", duration: 900, skillCheck: "analysis", risk: "Medium" },
      { id: "s3", label: "Recovery", description: "Extract and stabilize finds", duration: 600, skillCheck: "recovery", risk: "High" },
      { id: "s4", label: "Ascent", description: "Return through shifting paths", duration: 300, risk: "Medium" },
    ],
    rewards: {
      xp: 120,
      tokens: 5,
      materials: ["deep_fragment x2", "archive_core"],
      skillXp: [{ skill: "Analysis", amount: 30 }, { skill: "Recovery", amount: 25 }],
      possibleDrops: [
        { label: "Archive Listener", rarity: "rare", chance: 0.15 },
        { label: "Depth Touched", rarity: "epic", chance: 0.05 },
        { label: "Archive Halo", rarity: "epic", chance: 0.03 },
      ],
    },
  },
]

export const activeExpedition: ActiveExpedition = {
  id: "archive_dive",
  label: "Archive Dive",
  progress: 0.62,
  etaSeconds: 420,
  currentStage: 2,
  totalStages: 3,
  partyMembers: ["@you", "@palesignal"],
  startedAt: now - 1000 * 60 * 12,
  skillGains: [{ skill: "Analysis", xp: 12 }, { skill: "Recovery", xp: 8 }],
  log: [
    "Entering archive sector 7-C",
    "Archive fragment found",
    "Pattern stabilized",
    "Signal noise clearing...",
    "Stage 2: Search in progress",
  ],
}

export const skills: Skill[] = [
  {
    id: "scavenging",
    label: "Scavenging",
    summary: "Find overlooked salvage and extract more materials from ruins and debris fields.",
    level: 6,
    maxLevel: 10,
    locked: false,
    primaryExpeditions: ["scavenger_sweep"],
    effects: [
      { type: "material_yield", value: 5, description: "+5% material yield per level", appliesTo: ["scavenger_sweep"] },
      { type: "rare_chance", value: 2, description: "+2% rare salvage chance per level", appliesTo: ["scavenger_sweep"] },
    ],
  },
  {
    id: "analysis",
    label: "Analysis",
    summary: "Interpret archive data and recover intact fragments from corrupted sources.",
    level: 8,
    maxLevel: 10,
    locked: false,
    variant: "Deep Read",
    primaryExpeditions: ["archive_dive", "deep_archive"],
    effects: [
      { type: "rare_chance", value: 3, description: "+3% pristine fragment chance per level", appliesTo: ["archive_dive", "deep_archive"] },
      { type: "xp_bonus", value: 4, description: "+4% XP from archive expeditions per level", appliesTo: ["archive_dive", "deep_archive"] },
    ],
  },
  {
    id: "fabrication",
    label: "Fabrication",
    summary: "Craft equipment and convert raw materials into usable components.",
    level: 4,
    maxLevel: 10,
    locked: false,
    primaryExpeditions: [],
    effects: [
      { type: "craft_efficiency", value: 5, description: "+5% crafting material efficiency per level", appliesTo: [] },
      { type: "material_yield", value: 2, description: "+2% bonus materials when scrapping items per level", appliesTo: [] },
    ],
  },
  {
    id: "logistics",
    label: "Logistics",
    summary: "Manage supplies and optimize delivery routes for faster completion times.",
    level: 5,
    maxLevel: 10,
    locked: false,
    primaryExpeditions: ["courier_run"],
    effects: [
      { type: "expedition_time", value: -3, description: "-3% expedition time per level", appliesTo: ["courier_run"] },
      { type: "material_yield", value: 3, description: "+3% supply preservation per level", appliesTo: ["courier_run"] },
    ],
  },
  {
    id: "networking",
    label: "Networking",
    summary: "Build faction standing and coordinate multi-courier operations.",
    level: 3,
    maxLevel: 10,
    locked: false,
    primaryExpeditions: ["faction_relay"],
    effects: [
      { type: "faction_standing", value: 5, description: "+5% faction standing gain per level", appliesTo: ["faction_relay"] },
      { type: "party_bonus", value: 2, description: "+2% party XP bonus per level", appliesTo: [] },
    ],
  },
  {
    id: "surveying",
    label: "Surveying",
    summary: "Map relay signals and identify safe routes through hostile zones.",
    level: 7,
    maxLevel: 10,
    locked: false,
    variant: "Long Sight",
    primaryExpeditions: ["signal_trace"],
    effects: [
      { type: "expedition_time", value: -4, description: "-4% exploration time per level", appliesTo: ["signal_trace"] },
      { type: "rare_chance", value: 3, description: "+3% hidden route discovery per level", appliesTo: ["signal_trace"] },
    ],
  },
  {
    id: "recovery",
    label: "Recovery",
    summary: "Reduce expedition risks and improve safe extraction from dangerous zones.",
    level: 2,
    maxLevel: 10,
    locked: false,
    primaryExpeditions: ["deep_archive", "scavenger_sweep"],
    effects: [
      { type: "risk_reduction", value: 4, description: "-4% failure chance per level", appliesTo: ["deep_archive"] },
      { type: "material_yield", value: 3, description: "+3% materials retained on failed expeditions per level", appliesTo: [] },
    ],
  },
  {
    id: "security",
    label: "Security",
    summary: "Detect threats and mitigate hostile encounters during expeditions.",
    level: 0,
    maxLevel: 10,
    locked: true,
    primaryExpeditions: ["deep_archive", "scavenger_sweep"],
    effects: [
      { type: "risk_reduction", value: 5, description: "-5% hostile event chance per level", appliesTo: ["deep_archive", "scavenger_sweep"] },
      { type: "xp_bonus", value: 3, description: "+3% combat XP per level", appliesTo: [] },
    ],
  },
  {
    id: "cartography",
    label: "Cartography",
    summary: "Chart unknown territories and unlock hidden expedition routes.",
    level: 0,
    maxLevel: 10,
    locked: true,
    primaryExpeditions: ["signal_trace", "courier_run"],
    effects: [
      { type: "rare_chance", value: 5, description: "+5% chance to discover secret routes per level", appliesTo: ["signal_trace"] },
      { type: "expedition_time", value: -2, description: "-2% travel time on all expeditions per level", appliesTo: [] },
    ],
  },
]

export const inventory: InventoryItem[] = [
  {
    id: "relay_glass",
    label: "Relay Glass",
    aspect: "relay",
    rarity: "uncommon",
    qty: 4,
    identified: true,
    description: "A polished shard that holds a channel tone. Warm to the touch.",
  },
  {
    id: "archive_fragments",
    label: "Archive Fragments",
    aspect: "archive",
    rarity: "uncommon",
    qty: 6,
    identified: true,
    description: "Broken index packets. Reconstruct at the Archive station.",
  },
  {
    id: "salvage_plate",
    label: "Salvage Plate",
    aspect: "salvage",
    rarity: "common",
    qty: 2,
    identified: true,
    description: "Plated scrap, safe to handle. Good for trade.",
  },
  {
    id: "packed_rations",
    label: "Packed Rations",
    aspect: "supply",
    rarity: "common",
    qty: 8,
    identified: true,
    description: "Quiet calories. Suitable for longer routes.",
  },
  {
    id: "faction_seal",
    label: "Faction Seal",
    aspect: "relay",
    rarity: "rare",
    qty: 1,
    identified: true,
    description: "Authorizes one handoff inside a faction relay.",
  },
  {
    id: "unstable_imprint",
    label: "Unstable Imprint",
    aspect: "unknown",
    rarity: "epic",
    qty: 1,
    identified: false,
    description:
      "Signal irregular. Aspect not yet resolved. Run through the Archive to stabilize.",
  },
  {
    id: "glass_signal",
    label: "Glass Signal",
    aspect: "cosmetic",
    rarity: "epic",
    qty: 1,
    identified: true,
    description: "A chat flair. Your handle rings softly when you speak.",
  },
]

// Pre-defined static avatar configs to avoid hydration issues
// These are deterministic results from generateAvatarFromSeed
const playerAvatar: AvatarConfig = {
  seed: "@routetender.07",
  layers: [
    { type: "base", variant: 0, color: 2 },
    { type: "eyes", variant: 1, color: 1 },
    { type: "mouth", variant: 0 },
    { type: "hair", variant: 2, color: 3 },
    { type: "accessory", variant: 1 }, // glasses
    { type: "hat", variant: 0 },
    { type: "flair", variant: 0 },
  ],
}

const palesignalAvatar: AvatarConfig = {
  seed: "@Relay3e8f2",
  layers: [
    { type: "base", variant: 1, color: 1 },
    { type: "eyes", variant: 0, color: 2 },
    { type: "mouth", variant: 1 },
    { type: "hair", variant: 1, color: 1 },
    { type: "accessory", variant: 0 },
    { type: "hat", variant: 0 },
    { type: "flair", variant: 0 },
  ],
}

const archivistAvatar: AvatarConfig = {
  seed: "@Relay9d2e7",
  layers: [
    { type: "base", variant: 0, color: 3 },
    { type: "eyes", variant: 2, color: 0 },
    { type: "mouth", variant: 2 },
    { type: "hair", variant: 3, color: 2 },
    { type: "accessory", variant: 0 },
    { type: "hat", variant: 1 },
    { type: "flair", variant: 0 },
  ],
}

export const party: PartyMember[] = [
  {
  slot: 1,
  handle: "@Relay7a3b2",
  title: "Route Tender",
  titleRarity: "common",
  role: "Logistics",
  status: "ready",
  leader: true,
  avatar: playerAvatar,
  },
  {
  slot: 2,
  handle: "@Relay3e8f2",
  title: "Signal Keeper",
  titleRarity: "uncommon",
  role: "Surveying",
  status: "ready",
  avatar: palesignalAvatar,
  },
  {
  slot: 3,
  handle: "@Relay9d2e7",
  title: "Archive Listener",
  titleRarity: "rare",
  role: "Analysis",
  status: "idle",
  avatar: archivistAvatar,
  },
  // slot 4 is empty (invite slot)
]

export const recoveryResults: RecoveryResult[] = [
  {
    id: "r1",
    label: "Relay Flair",
    type: "chat_flair",
    rarity: "common",
    recoveredAt: now - 1000 * 60 * 60 * 4,
  },
  {
    id: "r2",
    label: "Signal Keeper",
    type: "title",
    rarity: "uncommon",
    recoveredAt: now - 1000 * 60 * 60 * 9,
  },
  {
    id: "r3",
    label: "Field Kit Schematic",
    type: "schematic",
    rarity: "common",
    recoveredAt: now - 1000 * 60 * 60 * 18,
  },
  {
    id: "r4",
    label: "Archive Listener",
    type: "title",
    rarity: "rare",
    recoveredAt: now - 1000 * 60 * 60 * 26,
  },
  {
    id: "r5",
    label: "Glass Signal",
    type: "cosmetic",
    rarity: "epic",
    recoveredAt: now - 1000 * 60 * 60 * 40,
  },
]

export const identity: Identity = {
  handle: "@Relay7a3b2",
  title: "Route Tender",
  titleRarity: "common",
  established: true,
  avatar: playerAvatar,
}

/** Shard currencies surfaced on the Archive page. */
export const shards = {
  relay_tokens: 14,
  deep_signals: 2,
  signal_salvage: 6,
}

export const quickActions: QuickAction[] = [
  {
    id: "qa1",
    label: "Claim Rewards",
    description: "Archive Dive complete",
    priority: "urgent",
    deeplink: { screen: "ops", tab: "expeditions" },
  },
  {
    id: "qa2",
    label: "Contract Deadline",
    description: "Salvage Run expires in 2h",
    priority: "urgent",
    deeplink: { screen: "contracts" },
  },
  {
    id: "qa3",
    label: "Faction Event",
    description: "Supply Drive active",
    priority: "normal",
    deeplink: { screen: "faction" },
  },
]

export const contracts: Contract[] = [
  // Expedition-aligned contracts
  {
    id: "c1",
    label: "Scavenger Sweep: Western Depot",
    issuer: "Hearth Wardens",
    description: "Complete a Scavenger Sweep expedition in the western depot. Recover salvage plates for outpost repairs.",
    reward: "40 XP, 2 Relay Tokens, Salvage Plate x2",
    deadline: "4h",
    status: "active",
  },
  {
    id: "c2",
    label: "Signal Trace: Sector 7-Alpha",
    issuer: "Open Roads Chorus",
    description: "Run a Signal Trace expedition to map relay nodes in sector 7-alpha. Surveying skill recommended.",
    reward: "35 XP, 1 Relay Token, Scrap Wire x3",
    deadline: "2h",
    status: "available",
  },
  {
    id: "c3",
    label: "Courier Run: Northern Route",
    issuer: "Open Roads Chorus",
    description: "Complete a Courier Run along the northern supply line. Logistics skill will improve delivery time.",
    reward: "30 XP, 1 Relay Token, Route Stamps x2",
    status: "available",
  },
  {
    id: "c4",
    label: "Archive Dive: Data Recovery",
    issuer: "Veiled Circle",
    description: "Undertake an Archive Dive to retrieve unstable data packets. Analysis skill required for fragment quality.",
    reward: "45 XP, 2 Relay Tokens, Archive Fragments x2",
    deadline: "6h",
    status: "available",
  },
  {
    id: "c5",
    label: "Deep Archive Expedition",
    issuer: "Veiled Circle",
    description: "Venture into the Deep Archive for rare fragments. High risk, 4-person party suggested. Analysis and Recovery skills essential.",
    reward: "120 XP, 5 Relay Tokens, Deep Fragment x2",
    deadline: "12h",
    status: "available",
  },
  // Faction-specific contracts
  {
    id: "c6",
    label: "Relay Network Repairs",
    issuer: "Crowned Courts",
    description: "Complete a Relay Maintenance expedition to restore signal integrity across sectors. Networking skill increases standing gain.",
    reward: "55 XP, 2 Relay Tokens, +25 Faction Standing",
    deadline: "8h",
    status: "available",
  },
  // Crafting/Materials contracts
  {
    id: "c7",
    label: "Fabrication Supply Run",
    issuer: "Hearth Wardens",
    description: "Gather materials from Scavenger Sweep expeditions for the hub's fabrication queue. Scavenging skill improves yield.",
    reward: "50 XP, 3 Relay Tokens, Salvage Plate x3",
    deadline: "10h",
    status: "available",
  },
  {
    id: "c8",
    label: "Archive Fragment Collection",
    issuer: "Veiled Circle",
    description: "Collect archive fragments from multiple Archive Dive expeditions for private study. Bonus for pristine fragments.",
    reward: "60 XP, 2 Deep Signals, Archive Core",
    deadline: "24h",
    status: "available",
  },
]

export const factionProjects: FactionProject[] = [
  {
    id: "fp1",
    label: "Outpost Reconstruction",
    description: "Contribute salvage plates from Scavenger Sweep expeditions to rebuild the western outpost. Hearth Wardens bonus: reduced material requirements.",
    progress: 847,
    goal: 1000,
    contributors: 23,
  },
  {
    id: "fp2",
    label: "Relay Network Expansion",
    description: "Complete Signal Trace and Faction Relay expeditions to extend coverage to sector 9. Open Roads bonus: faster route discovery.",
    progress: 312,
    goal: 500,
    contributors: 15,
  },
  {
    id: "fp3",
    label: "Deep Archive Cataloging",
    description: "Submit archive fragments from Archive Dive expeditions to build the faction index. Veiled Circle bonus: increased rare fragment chance.",
    progress: 156,
    goal: 400,
    contributors: 8,
  },
  {
    id: "fp4",
    label: "Courier Network Stabilization",
    description: "Complete Courier Run expeditions to stabilize supply lines across all sectors. Contributes route stamps and packed rations.",
    progress: 89,
    goal: 300,
    contributors: 12,
  },
]

// Unlocked vanity items
export const vanityItems: VanityItem[] = [
  // Accessories - Common
  { id: "v1", label: "Signal Glasses", layerType: "accessory", variant: 1, rarity: "common", unlocked: true, equipped: true },
  { id: "v11", label: "Basic Shades", layerType: "accessory", variant: 5, rarity: "common", unlocked: true, equipped: false },
  { id: "v12", label: "Dust Goggles", layerType: "accessory", variant: 6, rarity: "common", unlocked: false, equipped: false },
  { id: "v13", label: "Worn Bandana", layerType: "accessory", variant: 7, rarity: "common", unlocked: false, equipped: false },
  // Accessories - Uncommon
  { id: "v3", label: "Eyepatch", layerType: "accessory", variant: 2, rarity: "uncommon", unlocked: true, equipped: false },
  { id: "v14", label: "Scar Mark", layerType: "accessory", variant: 3, rarity: "uncommon", unlocked: false, equipped: false },
  { id: "v15", label: "Relay Earpiece", layerType: "accessory", variant: 8, rarity: "uncommon", unlocked: false, equipped: false },
  { id: "v16", label: "Signal Monocle", layerType: "accessory", variant: 9, rarity: "uncommon", unlocked: false, equipped: false },
  { id: "v17", label: "Route Mask", layerType: "accessory", variant: 10, rarity: "uncommon", unlocked: false, equipped: false },
  // Accessories - Rare
  { id: "v4", label: "Archive Visor", layerType: "accessory", variant: 4, rarity: "rare", unlocked: true, equipped: false },
  { id: "v18", label: "Deep Scanner", layerType: "accessory", variant: 11, rarity: "rare", unlocked: false, equipped: false },
  { id: "v19", label: "Rift Lens", layerType: "accessory", variant: 12, rarity: "rare", unlocked: false, equipped: false },
  { id: "v20", label: "Echo Mask", layerType: "accessory", variant: 13, rarity: "rare", unlocked: false, equipped: false },
  // Accessories - Epic
  { id: "v21", label: "Void Visor", layerType: "accessory", variant: 14, rarity: "epic", unlocked: false, equipped: false },
  { id: "v22", label: "Prismatic Lens", layerType: "accessory", variant: 15, rarity: "epic", unlocked: false, equipped: false },
  // Accessories - Legendary
  { id: "v23", label: "All-Seeing Eye", layerType: "accessory", variant: 16, rarity: "legendary", unlocked: false, equipped: false },

  // Hats - Common
  { id: "v2", label: "Route Cap", layerType: "hat", variant: 1, rarity: "common", unlocked: true, equipped: false },
  { id: "v24", label: "Dust Hood", layerType: "hat", variant: 7, rarity: "common", unlocked: false, equipped: false },
  { id: "v25", label: "Signal Beanie", layerType: "hat", variant: 8, rarity: "common", unlocked: false, equipped: false },
  { id: "v26", label: "Worn Helmet", layerType: "hat", variant: 9, rarity: "common", unlocked: false, equipped: false },
  // Hats - Uncommon
  { id: "v5", label: "Signal Antenna", layerType: "hat", variant: 3, rarity: "uncommon", unlocked: true, equipped: false },
  { id: "v27", label: "Relay Headset", layerType: "hat", variant: 10, rarity: "uncommon", unlocked: false, equipped: false },
  { id: "v28", label: "Archive Hood", layerType: "hat", variant: 11, rarity: "uncommon", unlocked: false, equipped: false },
  { id: "v29", label: "Scout Helm", layerType: "hat", variant: 12, rarity: "uncommon", unlocked: false, equipped: false },
  // Hats - Rare
  { id: "v6", label: "Relay Horns", layerType: "hat", variant: 4, rarity: "rare", unlocked: false, equipped: false },
  { id: "v30", label: "Drift Crown", layerType: "hat", variant: 13, rarity: "rare", unlocked: false, equipped: false },
  { id: "v31", label: "Echo Circlet", layerType: "hat", variant: 14, rarity: "rare", unlocked: false, equipped: false },
  { id: "v32", label: "Signal Crest", layerType: "hat", variant: 15, rarity: "rare", unlocked: false, equipped: false },
  // Hats - Epic
  { id: "v7", label: "Archive Halo", layerType: "hat", variant: 5, rarity: "epic", unlocked: false, equipped: false },
  { id: "v33", label: "Void Helm", layerType: "hat", variant: 16, rarity: "epic", unlocked: false, equipped: false },
  { id: "v34", label: "Rift Diadem", layerType: "hat", variant: 17, rarity: "epic", unlocked: false, equipped: false },
  // Hats - Legendary
  { id: "v8", label: "Crown of Routes", layerType: "hat", variant: 6, rarity: "legendary", unlocked: false, equipped: false },
  { id: "v35", label: "Primordial Antlers", layerType: "hat", variant: 18, rarity: "legendary", unlocked: false, equipped: false },

  // Flair - Common
  { id: "v36", label: "Soft Glow", layerType: "flair", variant: 4, rarity: "common", unlocked: false, equipped: false },
  { id: "v37", label: "Dust Motes", layerType: "flair", variant: 5, rarity: "common", unlocked: false, equipped: false },
  // Flair - Uncommon
  { id: "v38", label: "Signal Flicker", layerType: "flair", variant: 6, rarity: "uncommon", unlocked: false, equipped: false },
  { id: "v39", label: "Route Trails", layerType: "flair", variant: 7, rarity: "uncommon", unlocked: false, equipped: false },
  // Flair - Rare
  { id: "v10", label: "Sparkle Effect", layerType: "flair", variant: 3, rarity: "rare", unlocked: false, equipped: false },
  { id: "v40", label: "Echo Ripples", layerType: "flair", variant: 8, rarity: "rare", unlocked: false, equipped: false },
  { id: "v41", label: "Data Stream", layerType: "flair", variant: 9, rarity: "rare", unlocked: false, equipped: false },
  // Flair - Epic
  { id: "v9", label: "Static Aura", layerType: "flair", variant: 2, rarity: "epic", unlocked: false, equipped: false },
  { id: "v42", label: "Pulse Glow", layerType: "flair", variant: 1, rarity: "epic", unlocked: false, equipped: false },
  { id: "v43", label: "Void Shimmer", layerType: "flair", variant: 10, rarity: "epic", unlocked: false, equipped: false },
  // Flair - Legendary
  { id: "v44", label: "Prismatic Aura", layerType: "flair", variant: 11, rarity: "legendary", unlocked: false, equipped: false },
  { id: "v45", label: "Celestial Flame", layerType: "flair", variant: 12, rarity: "legendary", unlocked: false, equipped: false },

  // ============ MYTHIC / TRANSCENDENT TIER ============
  
  // Accessories - Mythic
  { id: "v50", label: "Voidtouched Gaze", layerType: "accessory", variant: 17, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v51", label: "Relay Sea Mask", layerType: "accessory", variant: 18, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v52", label: "Shardheart Visor", layerType: "accessory", variant: 19, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v53", label: "Eternal Courier's Mark", layerType: "accessory", variant: 20, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v54", label: "Primordial Echo", layerType: "accessory", variant: 21, rarity: "mythic", unlocked: false, equipped: false },

  // Hats - Mythic
  { id: "v55", label: "Crown of the Relay Sea", layerType: "hat", variant: 19, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v56", label: "Shardheart Coronet", layerType: "hat", variant: 20, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v57", label: "Eternal Courier's Crest", layerType: "hat", variant: 21, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v58", label: "Voidtouched Halo", layerType: "hat", variant: 22, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v59", label: "Primordial Echo Crown", layerType: "hat", variant: 23, rarity: "mythic", unlocked: false, equipped: false },

  // Flair - Mythic
  { id: "v60", label: "Relay Sea Aura", layerType: "flair", variant: 13, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v61", label: "Shardheart Radiance", layerType: "flair", variant: 14, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v62", label: "Eternal Courier's Light", layerType: "flair", variant: 15, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v63", label: "Voidtouched Presence", layerType: "flair", variant: 16, rarity: "mythic", unlocked: false, equipped: false },
  { id: "v64", label: "Primordial Resonance", layerType: "flair", variant: 17, rarity: "mythic", unlocked: false, equipped: false },
]

export const profile: Profile = {
  handle: "@routetender.07",
  title: {
    id: "route_tender",
    label: "Route Tender",
    rarity: "common",
    equipped: true,
  },
  faction: {
    id: "waykeepers",
    label: "Waykeepers",
    rank: 2,
    standing: 340,
    maxStanding: 500,
  },
  level: 14,
  xp: 2840,
  xpToNext: 3200,
  vanityItems: vanityItems,
  ownedTitles: [
    {
      id: "route_tender",
      label: "Route Tender",
      rarity: "common",
      equipped: true,
      source: "Waykeepers Rank 1",
    },
    {
      id: "signal_keeper",
      label: "Signal Keeper",
      rarity: "uncommon",
      equipped: false,
      source: "Archive Recovery",
    },
    {
      id: "archive_listener",
      label: "Archive Listener",
      rarity: "rare",
      equipped: false,
      source: "Archive Recovery",
    },
    {
      id: "relay_initiate",
      label: "Relay Initiate",
      rarity: "common",
      equipped: false,
      source: "First expedition",
    },
    {
      id: "pale_wanderer",
      label: "Pale Wanderer",
      rarity: "uncommon",
      equipped: false,
      source: "10 expeditions completed",
    },
    {
      id: "circuit_speaker",
      label: "Circuit Speaker",
      rarity: "uncommon",
      equipped: false,
      source: "Archive Collective Rank 2",
    },
    {
      id: "waystone_keeper",
      label: "Waystone Keeper",
      rarity: "rare",
      equipped: false,
      source: "Waykeepers Rank 3",
    },
    {
      id: "depth_touched",
      label: "Depth Touched",
      rarity: "epic",
      equipped: false,
      source: "First deep archive recovery",
    },
    {
      id: "gloam_signal_regent",
      label: "Gloam Signal Regent",
      rarity: "legendary",
      equipped: false,
      source: "Legendary archive recovery",
    },
    {
      id: "myth_relay_sea",
      label: "Myth of the Relay Sea",
      rarity: "mythic",
      equipped: false,
      source: "Transcendent achievement",
    },
  ],
  badges: [
    {
      id: "first_expedition",
      label: "First Steps",
      description: "Completed your first expedition.",
      earnedAt: now - 1000 * 60 * 60 * 24 * 14,
    },
    {
      id: "archive_recovered",
      label: "Archive Touched",
      description: "Recovered your first archive fragment.",
      earnedAt: now - 1000 * 60 * 60 * 24 * 10,
    },
    {
      id: "faction_joined",
      label: "Aligned",
      description: "Joined a faction.",
      earnedAt: now - 1000 * 60 * 60 * 24 * 7,
    },
  ],
  notifications: [
    {
      id: 1,
      title: "Expedition Complete",
      body: "Your Archive Dive has finished. Rewards are ready to claim.",
      priority: "high",
      state: "unread",
      deeplink: { screen: "expedition" },
      createdAt: now - 1000 * 60 * 12,
    },
    {
      id: 2,
      title: "Faction Standing",
      body: "Your standing with the Waykeepers increased by 45.",
      priority: "normal",
      state: "unread",
      createdAt: now - 1000 * 60 * 38,
    },
    {
      id: 3,
      title: "New Title Unlocked",
      body: "You earned the Signal Keeper title from signal recovery.",
      priority: "normal",
      state: "read",
      deeplink: { screen: "profile" },
      createdAt: now - 1000 * 60 * 60 * 2,
    },
    {
      id: 4,
      title: "Party Invite",
      body: "@palesignal invited you to join their party.",
      priority: "high",
      state: "read",
      deeplink: { screen: "party" },
      createdAt: now - 1000 * 60 * 60 * 4,
    },
  ],
}
