import type { CraftingRecipe, InventoryItem } from "@/lib/types"

// Base crafting materials that can be found or gathered
export const CRAFTING_MATERIALS: InventoryItem[] = [
  // Herbs
  { id: "moonpetal", label: "Moonpetal", aspect: "herb", rarity: "common", qty: 0, identified: true, description: "A pale flower that blooms in low light. Calming properties." },
  { id: "thornroot", label: "Thornroot", aspect: "herb", rarity: "common", qty: 0, identified: true, description: "Tough root with restorative properties. Bitter taste." },
  { id: "glowcap", label: "Glowcap Mushroom", aspect: "herb", rarity: "uncommon", qty: 0, identified: true, description: "Bioluminescent fungus. Enhances perception." },
  { id: "voidbloom", label: "Voidbloom", aspect: "herb", rarity: "rare", qty: 0, identified: true, description: "Grows only near signal anomalies. Highly potent." },
  { id: "starwort", label: "Starwort", aspect: "herb", rarity: "uncommon", qty: 0, identified: true, description: "Small white flowers with energy-restoring properties." },
  { id: "bittervine", label: "Bittervine", aspect: "herb", rarity: "common", qty: 0, identified: true, description: "A tangled vine with detoxifying properties." },
  
  // Minerals
  { id: "iron_dust", label: "Iron Dust", aspect: "mineral", rarity: "common", qty: 0, identified: true, description: "Fine metal particles. Base crafting component." },
  { id: "crystal_shard", label: "Crystal Shard", aspect: "mineral", rarity: "uncommon", qty: 0, identified: true, description: "Resonant crystal fragment. Amplifies effects." },
  { id: "void_salt", label: "Void Salt", aspect: "mineral", rarity: "rare", qty: 0, identified: true, description: "Crystallized from signal interference. Stabilizes compounds." },
  { id: "ember_ore", label: "Ember Ore", aspect: "mineral", rarity: "uncommon", qty: 0, identified: true, description: "Warm to the touch. Provides lasting heat." },
  { id: "deep_stone", label: "Deep Stone", aspect: "mineral", rarity: "rare", qty: 0, identified: true, description: "Dense mineral from archive depths. Extremely durable." },
  
  // Essences
  { id: "pure_water", label: "Pure Water", aspect: "essence", rarity: "common", qty: 0, identified: true, description: "Filtered water. Required for most recipes." },
  { id: "signal_essence", label: "Signal Essence", aspect: "essence", rarity: "uncommon", qty: 0, identified: true, description: "Condensed relay energy. Glows faintly." },
  { id: "void_essence", label: "Void Essence", aspect: "essence", rarity: "epic", qty: 0, identified: true, description: "Pure emptiness given form. Dangerous to handle." },
  { id: "life_essence", label: "Life Essence", aspect: "essence", rarity: "rare", qty: 0, identified: true, description: "Concentrated vitality. Heals and restores." },
  
  // Food ingredients
  { id: "dried_meat", label: "Dried Meat", aspect: "supply", rarity: "common", qty: 0, identified: true, description: "Preserved protein. Long shelf life." },
  { id: "wild_grain", label: "Wild Grain", aspect: "supply", rarity: "common", qty: 0, identified: true, description: "Foraged grain. Filling but bland." },
  { id: "honey_comb", label: "Honey Comb", aspect: "supply", rarity: "uncommon", qty: 0, identified: true, description: "Sweet and energizing. Natural preservative." },
  { id: "cave_fish", label: "Cave Fish", aspect: "supply", rarity: "uncommon", qty: 0, identified: true, description: "Pale fish from underground streams. Nutritious." },
  { id: "spice_blend", label: "Spice Blend", aspect: "supply", rarity: "uncommon", qty: 0, identified: true, description: "A mix of warming spices. Improves any dish." },
  { id: "fungal_flour", label: "Fungal Flour", aspect: "supply", rarity: "common", qty: 0, identified: true, description: "Ground mushroom base. Slightly nutty flavor." },
]

// Crafting recipes
export const CRAFTING_RECIPES: CraftingRecipe[] = [
  // ===== FOOD RECIPES =====
  {
    id: "trail_bread",
    label: "Trail Bread",
    category: "food",
    description: "Dense, filling bread perfect for long journeys.",
    ingredients: [
      { itemId: "wild_grain", label: "Wild Grain", qty: 3 },
      { itemId: "pure_water", label: "Pure Water", qty: 1 },
    ],
    output: {
      itemId: "trail_bread",
      label: "Trail Bread",
      aspect: "food",
      rarity: "common",
      qty: 2,
      description: "Dense, filling bread perfect for long journeys.",
      effects: ["+10 Stamina Recovery"],
    },
    craftTime: 30,
    unlocked: true,
  },
  {
    id: "honey_cake",
    label: "Honey Cake",
    category: "food",
    description: "A sweet treat that restores energy quickly.",
    ingredients: [
      { itemId: "wild_grain", label: "Wild Grain", qty: 2 },
      { itemId: "honey_comb", label: "Honey Comb", qty: 1 },
      { itemId: "pure_water", label: "Pure Water", qty: 1 },
    ],
    output: {
      itemId: "honey_cake",
      label: "Honey Cake",
      aspect: "food",
      rarity: "uncommon",
      qty: 1,
      description: "A sweet treat that restores energy quickly.",
      effects: ["+25 Energy", "+5% Movement Speed for 60s"],
    },
    craftTime: 45,
    unlocked: true,
  },
  {
    id: "courier_stew",
    label: "Courier's Stew",
    category: "food",
    description: "A hearty stew that warms the body and spirit.",
    ingredients: [
      { itemId: "dried_meat", label: "Dried Meat", qty: 2 },
      { itemId: "wild_grain", label: "Wild Grain", qty: 1 },
      { itemId: "spice_blend", label: "Spice Blend", qty: 1 },
      { itemId: "pure_water", label: "Pure Water", qty: 2 },
    ],
    output: {
      itemId: "courier_stew",
      label: "Courier's Stew",
      aspect: "food",
      rarity: "uncommon",
      qty: 1,
      description: "A hearty stew that warms the body and spirit.",
      effects: ["+50 Health", "+15 Stamina", "Cold Resistance for 5m"],
    },
    craftTime: 90,
    unlocked: true,
  },
  {
    id: "mushroom_risotto",
    label: "Mushroom Risotto",
    category: "food",
    description: "Creamy rice with cave mushrooms. A delicacy.",
    ingredients: [
      { itemId: "fungal_flour", label: "Fungal Flour", qty: 2 },
      { itemId: "glowcap", label: "Glowcap Mushroom", qty: 2 },
      { itemId: "pure_water", label: "Pure Water", qty: 1 },
    ],
    output: {
      itemId: "mushroom_risotto",
      label: "Mushroom Risotto",
      aspect: "food",
      rarity: "rare",
      qty: 1,
      description: "Creamy rice with cave mushrooms. A delicacy.",
      effects: ["+20 Perception for 10m", "+30 Health"],
    },
    craftTime: 120,
    requiredSkill: "scavenging",
    requiredSkillLevel: 2,
    unlocked: true,
  },
  {
    id: "signal_fish",
    label: "Signal-Seared Fish",
    category: "food",
    description: "Fish cooked using relay energy. Unique flavor.",
    ingredients: [
      { itemId: "cave_fish", label: "Cave Fish", qty: 2 },
      { itemId: "signal_essence", label: "Signal Essence", qty: 1 },
      { itemId: "spice_blend", label: "Spice Blend", qty: 1 },
    ],
    output: {
      itemId: "signal_fish",
      label: "Signal-Seared Fish",
      aspect: "food",
      rarity: "rare",
      qty: 1,
      description: "Fish cooked using relay energy. Unique flavor.",
      effects: ["+40 Health", "+20 Energy", "Signal Clarity +10% for 15m"],
    },
    craftTime: 60,
    unlocked: true,
  },
  
  // ===== POTION RECIPES =====
  {
    id: "minor_healing",
    label: "Minor Healing Draught",
    category: "potion",
    description: "A simple restorative tonic.",
    ingredients: [
      { itemId: "thornroot", label: "Thornroot", qty: 2 },
      { itemId: "pure_water", label: "Pure Water", qty: 1 },
    ],
    output: {
      itemId: "minor_healing",
      label: "Minor Healing Draught",
      aspect: "potion",
      rarity: "common",
      qty: 2,
      description: "A simple restorative tonic.",
      effects: ["Restore 30 Health instantly"],
    },
    craftTime: 20,
    unlocked: true,
  },
  {
    id: "stamina_tonic",
    label: "Stamina Tonic",
    category: "potion",
    description: "Reinvigorates tired muscles.",
    ingredients: [
      { itemId: "starwort", label: "Starwort", qty: 2 },
      { itemId: "honey_comb", label: "Honey Comb", qty: 1 },
      { itemId: "pure_water", label: "Pure Water", qty: 1 },
    ],
    output: {
      itemId: "stamina_tonic",
      label: "Stamina Tonic",
      aspect: "potion",
      rarity: "uncommon",
      qty: 1,
      description: "Reinvigorates tired muscles.",
      effects: ["+50 Stamina", "Stamina Regen +25% for 3m"],
    },
    craftTime: 45,
    unlocked: true,
  },
  {
    id: "antidote",
    label: "Antidote",
    category: "potion",
    description: "Purges toxins from the body.",
    ingredients: [
      { itemId: "bittervine", label: "Bittervine", qty: 2 },
      { itemId: "moonpetal", label: "Moonpetal", qty: 1 },
      { itemId: "pure_water", label: "Pure Water", qty: 1 },
    ],
    output: {
      itemId: "antidote",
      label: "Antidote",
      aspect: "potion",
      rarity: "common",
      qty: 2,
      description: "Purges toxins from the body.",
      effects: ["Cure Poison", "Toxin Immunity for 2m"],
    },
    craftTime: 30,
    unlocked: true,
  },
  {
    id: "perception_elixir",
    label: "Perception Elixir",
    category: "potion",
    description: "Sharpens the senses dramatically.",
    ingredients: [
      { itemId: "glowcap", label: "Glowcap Mushroom", qty: 2 },
      { itemId: "crystal_shard", label: "Crystal Shard", qty: 1 },
      { itemId: "pure_water", label: "Pure Water", qty: 1 },
    ],
    output: {
      itemId: "perception_elixir",
      label: "Perception Elixir",
      aspect: "potion",
      rarity: "rare",
      qty: 1,
      description: "Sharpens the senses dramatically.",
      effects: ["+30 Perception for 10m", "Reveal hidden paths"],
    },
    craftTime: 90,
    requiredSkill: "scavenging",
    requiredSkillLevel: 3,
    unlocked: true,
  },
  {
    id: "signal_clarity",
    label: "Signal Clarity Potion",
    category: "potion",
    description: "Attunes the mind to relay frequencies.",
    ingredients: [
      { itemId: "voidbloom", label: "Voidbloom", qty: 1 },
      { itemId: "signal_essence", label: "Signal Essence", qty: 2 },
      { itemId: "crystal_shard", label: "Crystal Shard", qty: 1 },
    ],
    output: {
      itemId: "signal_clarity",
      label: "Signal Clarity Potion",
      aspect: "potion",
      rarity: "epic",
      qty: 1,
      description: "Attunes the mind to relay frequencies.",
      effects: ["Signal Range +50%", "Interference Immunity for 15m"],
    },
    craftTime: 180,
    requiredSkill: "relay_tuning",
    requiredSkillLevel: 3,
    unlocked: false,
  },
  {
    id: "void_draught",
    label: "Void Draught",
    category: "potion",
    description: "A dangerous concoction that lets you slip between signals.",
    ingredients: [
      { itemId: "void_essence", label: "Void Essence", qty: 1 },
      { itemId: "voidbloom", label: "Voidbloom", qty: 2 },
      { itemId: "void_salt", label: "Void Salt", qty: 1 },
      { itemId: "life_essence", label: "Life Essence", qty: 1 },
    ],
    output: {
      itemId: "void_draught",
      label: "Void Draught",
      aspect: "potion",
      rarity: "legendary",
      qty: 1,
      description: "A dangerous concoction that lets you slip between signals.",
      effects: ["Phase Walk for 30s", "Bypass relay locks", "-20% Max Health for 5m"],
    },
    craftTime: 300,
    requiredSkill: "relay_tuning",
    requiredSkillLevel: 5,
    unlocked: false,
  },
  
  // ===== COMPONENT RECIPES =====
  {
    id: "refined_crystal",
    label: "Refined Crystal",
    category: "component",
    description: "A purified crystal ready for advanced crafting.",
    ingredients: [
      { itemId: "crystal_shard", label: "Crystal Shard", qty: 3 },
      { itemId: "void_salt", label: "Void Salt", qty: 1 },
    ],
    output: {
      itemId: "refined_crystal",
      label: "Refined Crystal",
      aspect: "material",
      rarity: "rare",
      qty: 1,
      description: "A purified crystal ready for advanced crafting.",
    },
    craftTime: 60,
    unlocked: true,
  },
  {
    id: "signal_catalyst",
    label: "Signal Catalyst",
    category: "component",
    description: "Concentrated signal energy in solid form.",
    ingredients: [
      { itemId: "signal_essence", label: "Signal Essence", qty: 3 },
      { itemId: "ember_ore", label: "Ember Ore", qty: 1 },
      { itemId: "crystal_shard", label: "Crystal Shard", qty: 1 },
    ],
    output: {
      itemId: "signal_catalyst",
      label: "Signal Catalyst",
      aspect: "material",
      rarity: "epic",
      qty: 1,
      description: "Concentrated signal energy in solid form.",
    },
    craftTime: 120,
    requiredSkill: "relay_tuning",
    requiredSkillLevel: 2,
    unlocked: true,
  },
  {
    id: "void_alloy",
    label: "Void Alloy Ingot",
    category: "component",
    description: "Metal infused with void essence. Lightweight yet strong.",
    ingredients: [
      { itemId: "iron_dust", label: "Iron Dust", qty: 5 },
      { itemId: "void_salt", label: "Void Salt", qty: 2 },
      { itemId: "deep_stone", label: "Deep Stone", qty: 1 },
    ],
    output: {
      itemId: "void_alloy",
      label: "Void Alloy Ingot",
      aspect: "material",
      rarity: "epic",
      qty: 1,
      description: "Metal infused with void essence. Lightweight yet strong.",
    },
    craftTime: 180,
    requiredSkill: "security",
    requiredSkillLevel: 3,
    unlocked: false,
  },
  
  // ===== GEAR RECIPES =====
  {
    id: "signal_lantern",
    label: "Signal Lantern",
    category: "gear",
    description: "A lantern that reveals hidden signals.",
    ingredients: [
      { itemId: "iron_dust", label: "Iron Dust", qty: 3 },
      { itemId: "signal_essence", label: "Signal Essence", qty: 2 },
      { itemId: "crystal_shard", label: "Crystal Shard", qty: 2 },
    ],
    output: {
      itemId: "signal_lantern",
      label: "Signal Lantern",
      aspect: "relay",
      rarity: "rare",
      qty: 1,
      description: "A lantern that reveals hidden signals.",
      effects: ["Reveals hidden relays", "Light radius +50%"],
    },
    craftTime: 150,
    requiredSkill: "relay_tuning",
    requiredSkillLevel: 2,
    unlocked: true,
  },
  {
    id: "courier_pack",
    label: "Courier's Pack",
    category: "gear",
    description: "An expanded pack for serious expeditions.",
    ingredients: [
      { itemId: "dried_meat", label: "Dried Meat", qty: 2 }, // leather substitute
      { itemId: "iron_dust", label: "Iron Dust", qty: 3 },
      { itemId: "deep_stone", label: "Deep Stone", qty: 1 },
    ],
    output: {
      itemId: "courier_pack",
      label: "Courier's Pack",
      aspect: "relay",
      rarity: "rare",
      qty: 1,
      description: "An expanded pack for serious expeditions.",
      effects: ["+10 Inventory Slots", "+5% Loot Find"],
    },
    craftTime: 200,
    unlocked: true,
  },
  
  // ===== SPECIAL RECIPES =====
  {
    id: "archive_key",
    label: "Archive Key",
    category: "special",
    description: "Unlocks sealed archive sections.",
    ingredients: [
      { itemId: "void_salt", label: "Void Salt", qty: 2 },
      { itemId: "signal_essence", label: "Signal Essence", qty: 3 },
      { itemId: "deep_stone", label: "Deep Stone", qty: 1 },
      { itemId: "crystal_shard", label: "Crystal Shard", qty: 2 },
    ],
    output: {
      itemId: "archive_key",
      label: "Archive Key",
      aspect: "archive",
      rarity: "epic",
      qty: 1,
      description: "Unlocks sealed archive sections.",
      effects: ["Single use", "Access restricted archives"],
    },
    craftTime: 240,
    requiredSkill: "cartography",
    requiredSkillLevel: 1,
    unlocked: false,
  },
  {
    id: "relay_beacon",
    label: "Personal Relay Beacon",
    category: "special",
    description: "Creates a temporary personal waypoint.",
    ingredients: [
      { itemId: "signal_essence", label: "Signal Essence", qty: 5 },
      { itemId: "void_essence", label: "Void Essence", qty: 1 },
      { itemId: "ember_ore", label: "Ember Ore", qty: 2 },
      { itemId: "iron_dust", label: "Iron Dust", qty: 4 },
    ],
    output: {
      itemId: "relay_beacon",
      label: "Personal Relay Beacon",
      aspect: "relay",
      rarity: "legendary",
      qty: 1,
      description: "Creates a temporary personal waypoint.",
      effects: ["Place personal relay", "Fast travel once", "Expires in 24h"],
    },
    craftTime: 360,
    requiredSkill: "relay_tuning",
    requiredSkillLevel: 5,
    unlocked: false,
  },
]

// Category labels and colors
export const CATEGORY_CONFIG: Record<string, { label: string; color: string; icon: string }> = {
  food: { label: "Food", color: "var(--color-amber)", icon: "◉" },
  potion: { label: "Potions", color: "var(--color-green)", icon: "◈" },
  gear: { label: "Gear", color: "var(--color-cyan)", icon: "◆" },
  component: { label: "Components", color: "var(--color-muted)", icon: "◇" },
  special: { label: "Special", color: "var(--color-violet-bright)", icon: "★" },
}
